apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-ezkk
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-ezkk
    app.kubernetes.io/part-of: ci1t-830-0033-app
  name: devfile-sample-ezkk
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-ezkk
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-ezkk
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci1t-830-0033-tenant/ci1t-830-0033-app/devfile-sample-ezkk@sha256:4ac5f38b1d85d99e05932e22bd694fb370b974e83000e3f146f21e4557924a54
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
